name: build-project
on: push
#
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: install nix
        uses: cachix/install-nix-action@master
      - run: nix build

  build-dev-shell:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: install nix
        uses: cachix/install-nix-action@master
      - run: nix build .#devShells.x86_64-linux.default
